Repository valkey-io/valkey-py, pull requests merged in 2024-12, with the labels that each got.

#135 update the return type of scan family
  valkey/commands/core.py
Labels: typing

#139 update typing for copy
  valkey/commands/core.py
Labels: not-for-changelog, typing

#148 Add async class aliases for redis-py compatibility
  valkey/asyncio/__init__.py
Labels: enhancement

#147 Add more test cases
  tests/test_commands.py
Labels: not-for-changelog

#144 fixed problems in #143
  tests/test_commands.py
  valkey/commands/core.py
Labels: enhancement

#154 fixed type hints of hash methods
  valkey/commands/core.py
Labels: typing
